<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.bite</string>
    <key>name</key>
    <string>Bite</string>
    <key>fileTypes</key>
    <array>
      <string>bite</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^\s*#\s*region|^\s*/\*|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
    <key>foldingStopMarker</key>
    <string>^\s*#\s*endregion|^\s*\*/|^\s*\}</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using.cs</string>
          </dict>
        </dict>
        <key>begin</key>
        <string>^\s*(using)\b\s*</string>
        <key>end</key>
        <string>\s*(?:$|(;))</string>
        <key>name</key>
        <string>meta.keyword.using.cs</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.using.cs</string>
          </dict>
        </dict>
        <key>begin</key>
        <string>^\s*(import)\b\s*</string>
        <key>end</key>
        <string>\s*(?:$|(;))</string>
        <key>name</key>
        <string>meta.keyword.using.cs</string>
      </dict>
     <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.namespace.cs</string>
          </dict>
        </dict>
        <key>begin</key>
        <string>^\s*(module)\b\s*</string>
        <key>end</key>
        <string>\s*(?:$|(;))</string>
        <key>name</key>
        <string>meta.keyword.namespace.cs</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.cs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.block.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>builtinTypes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(bool|byte|sbyte|char|decimal|double|float|int|uint|long|ulong|object|short|ushort|string|void|class|struct|enum|interface)\b</string>
            <key>name</key>
            <string>storage.type.cs</string>
          </dict>
        </array>
      </dict>
      <key>class</key>
      <dict>
        <key>begin</key>
        <string>(?=\w?[\w\s]*(?:class|struct|interface|function|enum)\s+\w+)</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.class.end.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.class.cs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.cs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(class|struct|interface|function|enum)\s+(\w+)</string>
            <key>name</key>
            <string>meta.class.identifier.cs</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:</string>
            <key>end</key>
            <string>(?={)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.cs</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>\s*,?([A-Za-z_]\w*)\b</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.class.begin.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=})</string>
            <key>name</key>
            <string>meta.class.body.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#method</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#preprocessor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#builtinTypes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#documentation</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>///</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$\n?</string>
            <key>name</key>
            <string>comment.block.documentation.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.xml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/\n?</string>
            <key>name</key>
            <string>comment.block.cs</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.cs</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false|null|this|base)\b</string>
            <key>name</key>
            <string>constant.language.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
            <key>name</key>
            <string>constant.numeric.cs</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>@"([^"]|"")*"</string>
            <key>name</key>
            <string>string.quoted.double.literal.cs</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.cs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.cs</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.cs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.cs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.cs</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(if|else|while|for|foreach|in|do|return|continue|break|switch|case|default|goto|throw|try|catch|finally|lock|yield|await)\b</string>
            <key>name</key>
            <string>keyword.control.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(from|where|select|group|into|orderby|join|let|on|equals|by|ascending|descending)\b</string>
            <key>name</key>
            <string>keyword.linq.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(new|is|as|using|checked|unchecked|typeof|sizeof|override|readonly|stackalloc)\b</string>
            <key>name</key>
            <string>keyword.operator.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(event|delegate|fixed|add|remove|set|get|value)\b</string>
            <key>name</key>
            <string>keyword.other.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(var)\b</string>
            <key>name</key>
            <string>storage.type.var.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[@]\b(var|event|delegate|add|remove|set|get|value|new|is|as|using|checked|unchecked|typeof|sizeof |override|readonly|stackalloc|from|where|select|group|into|orderby|join|let|on|equals|by|ascending|descending |if|else|while|for|foreach|in|do|return|continue|break|switch|case|default|goto|throw|try|catch|finally|lock|yield|await)\b</string>
            <key>name</key>
            <string>meta.class.body.cs</string>
          </dict>
        </array>
      </dict>
      <key>method</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>name</key>
            <string>meta.method.annotation.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#preprocessor</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#builtinTypes</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=\bnew\s+)(?=[\w&lt;].*\s+)(?=[^=]+\()</string>
            <key>end</key>
            <string>(?={|;)</string>
            <key>name</key>
            <string>meta.new-object.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!=|=\s)(?!new)(?!.*(=|\/\/|\/\*).*\()(?=[\w&lt;].*\s+.+\()</string>
            <key>end</key>
            <string>(})|(?=;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.method.end.cs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.method.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage-modifiers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#builtinTypes</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>([\w.]+)\s*\(</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.cs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>name</key>
                <string>meta.method.identifier.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#parameters</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#constants</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?=\w.*\s+[\w.]+\s*\()</string>
                <key>end</key>
                <string>(?=[\w.]+\s*\()</string>
                <key>name</key>
                <string>meta.method.return-type.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#builtinTypes</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>:\s*(this|base)\s*\(</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>constant.language.cs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>name</key>
                <string>meta.method.base-call.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#builtinTypes</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>{</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.method.begin.cs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=})</string>
                <key>name</key>
                <string>meta.method.body.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#code</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?!new)(?=[\w&lt;].*\s+)(?=[^=]+\{)</string>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.property.end.cs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.property.cs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage-modifiers</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>([\w.]+)\s*(?={)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.cs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?={)</string>
                <key>name</key>
                <string>meta.method.identifier.cs</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>(?=\w.*\s+[\w.]+\s*\{)</string>
                <key>end</key>
                <string>(?=[\w.]+\s*\{)</string>
                <key>name</key>
                <string>meta.method.return-type.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#builtinTypes</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>{</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.property.begin.cs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=})</string>
                <key>name</key>
                <string>meta.method.body.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#code</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>method-call</key>
      <dict>
        <key>begin</key>
        <string>([\w$]+)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.method.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method-parameters.begin.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.method-parameters.end.cs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.method-call.cs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.definition.seperator.parameter.cs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#code</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>begin</key>
        <string>\b(ref|params|out)?\s*\b([\w.\[\]]+)\s+(\w+)\s*(=)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.modifier.cs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.generic.cs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.function.cs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.cs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?:(,)|(?=[\)]))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.separator.parameter.cs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block</string>
          </dict>
        </array>
      </dict>
      <key>preprocessor</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.toc-list.region.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*#\s*(region)\b\s*([^\/]+)\s</string>
            <key>name</key>
            <string>meta.preprocessor.cs</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.preprocessor.cs</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*#\s*(define|undef|if|elif)\b\s*(\S*)</string>
            <key>name</key>
            <string>meta.preprocessor.cs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*#\s*(if|else|elif|endif|define|undef|warning|error|line|pragma|region|endregion)\b\s*([^\/]+)\s</string>
            <key>name</key>
            <string>meta.preprocessor.cs</string>
          </dict>
        </array>
      </dict>
      <key>storage-modifiers</key>
      <dict>
        <key>match</key>
        <string>\b(event|delegate|internal|public|protected|private|static|const|new|sealed|abstract|virtual|override|extern|unsafe|readonly|volatile|implicit|explicit|operator|async|partial)\b</string>
        <key>name</key>
        <string>storage.modifier.cs</string>
      </dict>
    </dict>
  </dict>
</plist>